/**
 * List of countries
 * following  ISO-3166-1: Alpha-2 Codes
 *
 * @type {Array}
 */
var countries = [
    { text: "AFGHANISTAN", value: "AF" },
    { text: "AFRIQUE DU SUD", value: "ZA" },
    { text: "ÅLAND, ÎLES", value: "AX" },
    { text: "ALBANIE", value: "AL" },
    { text: "ALGÉRIE", value: "DZ" },
    { text: "ALLEMAGNE", value: "DE" },
    { text: "ANDORRE", value: "AD" },
    { text: "ANGOLA", value: "AO" },
    { text: "ANGUILLA", value: "AI" },
    { text: "ANTARCTIQUE", value: "AQ" },
    { text: "ANTIGUA-ET-BARBUDA", value: "AG" },
    { text: "ANTILLES NÉERLANDAISES", value: "AN" },
    { text: "ARABIE SAOUDITE", value: "SA" },
    { text: "ARGENTINE", value: "AR" },
    { text: "ARMÉNIE", value: "AM" },
    { text: "ARUBA", value: "AW" },
    { text: "AUSTRALIE", value: "AU" },
    { text: "AUTRICHE", value: "AT" },
    { text: "AZERBAÏDJAN", value: "AZ" },
    { text: "BAHAMAS", value: "BS" },
    { text: "BAHREÏN", value: "BH" },
    { text: "BANGLADESH", value: "BD" },
    { text: "BARBADE", value: "BB" },
    { text: "BÉLARUS", value: "BY" },
    { text: "BELGIQUE", value: "BE" },
    { text: "BELIZE", value: "BZ" },
    { text: "BÉNIN", value: "BJ" },
    { text: "BERMUDES", value: "BM" },
    { text: "BHOUTAN", value: "BT" },
    { text: "BOLIVIE", value: "BO" },
    { text: "BOSNIE-HERZÉGOVINE", value: "BA" },
    { text: "BOTSWANA", value: "BW" },
    { text: "BOUVET, ÎLE", value: "BV" },
    { text: "BRÉSIL", value: "BR" },
    { text: "BRUNÉI DARUSSALAM", value: "BN" },
    { text: "BULGARIE", value: "BG" },
    { text: "BURKINA FASO", value: "BF" },
    { text: "BURUNDI", value: "BI" },
    { text: "CAÏMANES, ÎLES", value: "KY" },
    { text: "CAMBODGE", value: "KH" },
    { text: "CAMEROUN", value: "CM" },
    { text: "CANADA", value: "CA" },
    { text: "CAP-VERT", value: "CV" },
    { text: "CENTRAFRICAINE, RÉPUBLIQUE", value: "CF" },
    { text: "CHILI", value: "CL" },
    { text: "CHINE", value: "CN" },
    { text: "CHRISTMAS, ÎLE", value: "CX" },
    { text: "CHYPRE", value: "CY" },
    { text: "COCOS (KEELING), ÎLES", value: "CC" },
    { text: "COLOMBIE", value: "CO" },
    { text: "COMORES", value: "KM" },
    { text: "CONGO", value: "CG" },
    { text: "CONGO, LA RÉPUBLIQUE DÉMOCRATIQUE DU", value: "CD" },
    { text: "COOK, ÎLES", value: "CK" },
    { text: "CORÉE, RÉPUBLIQUE DE", value: "KR" },
    { text: "CORÉE, RÉPUBLIQUE POPULAIRE DÉMOCRATIQUE DE", value: "KP" },
    { text: "COSTA RICA", value: "CR" },
    { text: "CÔTE D'IVOIRE", value: "CI" },
    { text: "CROATIE", value: "HR" },
    { text: "CUBA", value: "CU" },
    { text: "DANEMARK", value: "DK" },
    { text: "DJIBOUTI", value: "DJ" },
    { text: "DOMINICAINE, RÉPUBLIQUE", value: "DO" },
    { text: "DOMINIQUE", value: "DM" },
    { text: "ÉGYPTE", value: "EG" },
    { text: "EL SALVADOR", value: "SV" },
    { text: "ÉMIRATS ARABES UNIS", value: "AE" },
    { text: "ÉQUATEUR", value: "EC" },
    { text: "ÉRYTHRÉE", value: "ER" },
    { text: "ESPAGNE", value: "ES" },
    { text: "ESTONIE", value: "EE" },
    { text: "ÉTATS-UNIS", value: "US" },
    { text: "ÉTHIOPIE", value: "ET" },
    { text: "FALKLAND, ÎLES (MALVINAS)", value: "FK" },
    { text: "FÉROÉ, ÎLES", value: "FO" },
    { text: "FIDJI", value: "FJ" },
    { text: "FINLANDE", value: "FI" },
    { text: "FRANCE", value: "FR" },
    { text: "GABON", value: "GA" },
    { text: "GAMBIE", value: "GM" },
    { text: "GÉORGIE", value: "GE" },
    { text: "GÉORGIE DU SUD ET LES ÎLES SANDWICH DU SUD", value: "GS" },
    { text: "GHANA", value: "GH" },
    { text: "GIBRALTAR", value: "GI" },
    { text: "GRÈCE", value: "GR" },
    { text: "GRENADE", value: "GD" },
    { text: "GROENLAND", value: "GL" },
    { text: "GUADELOUPE", value: "GP" },
    { text: "GUAM", value: "GU" },
    { text: "GUATEMALA", value: "GT" },
    { text: "GUERNESEY", value: "GG" },
    { text: "GUINÉE", value: "GN" },
    { text: "GUINÉE-BISSAU", value: "GW" },
    { text: "GUINÉE ÉQUATORIALE", value: "GQ" },
    { text: "GUYANA", value: "GY" },
    { text: "GUYANE FRANÇAISE", value: "GF" },
    { text: "HAÏTI", value: "HT" },
    { text: "HEARD, ÎLE ET MCDONALD, ÎLES", value: "HM" },
    { text: "HONDURAS", value: "HN" },
    { text: "HONG-KONG", value: "HK" },
    { text: "HONGRIE", value: "HU" },
    { text: "ÎLE DE MAN", value: "IM" },
    { text: "ÎLES MINEURES ÉLOIGNÉES DES ÉTATS-UNIS", value: "UM" },
    { text: "ÎLES VIERGES BRITANNIQUES", value: "VG" },
    { text: "ÎLES VIERGES DES ÉTATS-UNIS", value: "VI" },
    { text: "INDE", value: "IN" },
    { text: "INDONÉSIE", value: "ID" },
    { text: "IRAN, RÉPUBLIQUE ISLAMIQUE D'", value: "IR" },
    { text: "IRAQ", value: "IQ" },
    { text: "IRLANDE", value: "IE" },
    { text: "ISLANDE", value: "IS" },
    { text: "ISRAËL", value: "IL" },
    { text: "ITALIE", value: "IT" },
    { text: "JAMAÏQUE", value: "JM" },
    { text: "JAPON", value: "JP" },
    { text: "JERSEY", value: "JE" },
    { text: "JORDANIE", value: "JO" },
    { text: "KAZAKHSTAN", value: "KZ" },
    { text: "KENYA", value: "KE" },
    { text: "KIRGHIZISTAN", value: "KG" },
    { text: "KIRIBATI", value: "KI" },
    { text: "KOWEÏT", value: "KW" },
    { text: "LAO, RÉPUBLIQUE DÉMOCRATIQUE POPULAIRE", value: "LA" },
    { text: "LESOTHO", value: "LS" },
    { text: "LETTONIE", value: "LV" },
    { text: "LIBAN", value: "LB" },
    { text: "LIBÉRIA", value: "LR" },
    { text: "LIBYENNE, JAMAHIRIYA ARABE", value: "LY" },
    { text: "LIECHTENSTEIN", value: "LI" },
    { text: "LITUANIE", value: "LT" },
    { text: "LUXEMBOURG", value: "LU" },
    { text: "MACAO", value: "MO" },
    { text: "MACÉDOINE, L'EX-RÉPUBLIQUE YOUGOSLAVE DE", value: "MK" },
    { text: "MADAGASCAR", value: "MG" },
    { text: "MALAISIE", value: "MY" },
    { text: "MALAWI", value: "MW" },
    { text: "MALDIVES", value: "MV" },
    { text: "MALI", value: "ML" },
    { text: "MALTE", value: "MT" },
    { text: "MARIANNES DU NORD, ÎLES", value: "MP" },
    { text: "MAROC", value: "MA" },
    { text: "MARSHALL, ÎLES", value: "MH" },
    { text: "MARTINIQUE", value: "MQ" },
    { text: "MAURICE", value: "MU" },
    { text: "MAURITANIE", value: "MR" },
    { text: "MAYOTTE", value: "YT" },
    { text: "MEXIQUE", value: "MX" },
    { text: "MICRONÉSIE, ÉTATS FÉDÉRÉS DE", value: "FM" },
    { text: "MOLDOVA, RÉPUBLIQUE DE", value: "MD" },
    { text: "MONACO", value: "MC" },
    { text: "MONGOLIE", value: "MN" },
    { text: "MONTSERRAT", value: "MS" },
    { text: "MOZAMBIQUE", value: "MZ" },
    { text: "MYANMAR", value: "MM" },
    { text: "NAMIBIE", value: "NA" },
    { text: "NAURU", value: "NR" },
    { text: "NÉPAL", value: "NP" },
    { text: "NICARAGUA", value: "NI" },
    { text: "NIGER", value: "NE" },
    { text: "NIGÉRIA", value: "NG" },
    { text: "NIUÉ", value: "NU" },
    { text: "NORFOLK, ÎLE", value: "NF" },
    { text: "NORVÈGE", value: "NO" },
    { text: "NOUVELLE-CALÉDONIE", value: "NC" },
    { text: "NOUVELLE-ZÉLANDE", value: "NZ" },
    { text: "OCÉAN INDIEN, TERRITOIRE BRITANNIQUE DE L'", value: "IO" },
    { text: "OMAN", value: "OM" },
    { text: "OUGANDA", value: "UG" },
    { text: "OUZBÉKISTAN", value: "UZ" },
    { text: "PAKISTAN", value: "PK" },
    { text: "PALAOS", value: "PW" },
    { text: "PALESTINIEN OCCUPÉ, TERRITOIRE", value: "PS" },
    { text: "PANAMA", value: "PA" },
    { text: "PAPOUASIE-NOUVELLE-GUINÉE", value: "PG" },
    { text: "PARAGUAY", value: "PY" },
    { text: "PAYS-BAS", value: "NL" },
    { text: "PÉROU", value: "PE" },
    { text: "PHILIPPINES", value: "PH" },
    { text: "PITCAIRN", value: "PN" },
    { text: "POLOGNE", value: "PL" },
    { text: "POLYNÉSIE FRANÇAISE", value: "PF" },
    { text: "PORTO RICO", value: "PR" },
    { text: "PORTUGAL", value: "PT" },
    { text: "QATAR", value: "QA" },
    { text: "RÉUNION", value: "RE" },
    { text: "ROUMANIE", value: "RO" },
    { text: "ROYAUME-UNI", value: "GB" },
    { text: "RUSSIE, FÉDÉRATION DE", value: "RU" },
    { text: "RWANDA", value: "RW" },
    { text: "SAHARA OCCIDENTAL", value: "EH" },
    { text: "SAINTE-HÉLÈNE", value: "SH" },
    { text: "SAINTE-LUCIE", value: "LC" },
    { text: "SAINT-KITTS-ET-NEVIS", value: "KN" },
    { text: "SAINT-MARIN", value: "SM" },
    { text: "SAINT-PIERRE-ET-MIQUELON", value: "PM" },
    { text: "SAINT-SIÈGE (ÉTAT DE LA CITÉ DU VATICAN)", value: "VA" },
    { text: "SAINT-VINCENT-ET-LES GRENADINES", value: "VC" },
    { text: "SALOMON, ÎLES", value: "SB" },
    { text: "SAMOA", value: "WS" },
    { text: "SAMOA AMÉRICAINES", value: "AS" },
    { text: "SAO TOMÉ-ET-PRINCIPE", value: "ST" },
    { text: "SÉNÉGAL", value: "SN" },
    { text: "SERBIE-ET-MONTÉNÉGRO", value: "CS" },
    { text: "SEYCHELLES", value: "SC" },
    { text: "SIERRA LEONE", value: "SL" },
    { text: "SINGAPOUR", value: "SG" },
    { text: "SLOVAQUIE", value: "SK" },
    { text: "SLOVÉNIE", value: "SI" },
    { text: "SOMALIE", value: "SO" },
    { text: "SOUDAN", value: "SD" },
    { text: "SRI LANKA", value: "LK" },
    { text: "SUÈDE", value: "SE" },
    { text: "SUISSE", value: "CH" },
    { text: "SURINAME", value: "SR" },
    { text: "SVALBARD ET ÎLE JAN MAYEN", value: "SJ" },
    { text: "SWAZILAND", value: "SZ" },
    { text: "SYRIENNE, RÉPUBLIQUE ARABE", value: "SY" },
    { text: "TADJIKISTAN", value: "TJ" },
    { text: "TAÏWAN, PROVINCE DE CHINE", value: "TW" },
    { text: "TANZANIE, RÉPUBLIQUE-UNIE DE", value: "TZ" },
    { text: "TCHAD", value: "TD" },
    { text: "TCHÈQUE, RÉPUBLIQUE", value: "CZ" },
    { text: "TERRES AUSTRALES FRANÇAISES", value: "TF" },
    { text: "THAÏLANDE", value: "TH" },
    { text: "TIMOR-LESTE", value: "TL" },
    { text: "TOGO", value: "TG" },
    { text: "TOKELAU", value: "TK" },
    { text: "TONGA", value: "TO" },
    { text: "TRINITÉ-ET-TOBAGO", value: "TT" },
    { text: "TUNISIE", value: "TN" },
    { text: "TURKMÉNISTAN", value: "TM" },
    { text: "TURKS ET CAÏQUES, ÎLES", value: "TC" },
    { text: "TURQUIE", value: "TR" },
    { text: "TUVALU", value: "TV" },
    { text: "UKRAINE", value: "UA" },
    { text: "URUGUAY", value: "UY" },
    { text: "VANUATU", value: "VU" },
    { text: "VENEZUELA", value: "VE" },
    { text: "VIET NAM", value: "VN" },
    { text: "WALLIS ET FUTUNA", value: "WF" },
    { text: "YÉMEN", value: "YE" },
    { text: "ZAMBIE", value: "ZM" },
    { text: "ZIMBABWE", value: "ZW" }
];
